import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderLogo from "./HeaderLogo";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-[#0D1A3A] min-h-screen flex flex-col items-center`}>
        <HeaderLogo />
        <main className="w-full flex-1 flex flex-col items-center justify-start">
          {children}
        </main>
      </body>
    </html>
  );
}
